AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  late-checkout-api

  Sample SAM Template for late-checkout-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.8
    Architectures:
      - x86_64

Resources:
  DynamoDBSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/search/
      Handler: app.lambda_handler
      Timeout: 120
      Policies:
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref LambdaLayer
  ScrapingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/scraping/
      Handler: app.lambda_handler
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref LambdaLayer
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: sfn-late-checkout
      DefinitionUri: statemachine/sfn.asl.json
      DefinitionSubstitutions:
        SearchLambdaFunction: !GetAtt DynamoDBSearchFunction.Arn
        ScrapingLambdaFunction: !GetAtt ScrapingFunction.Arn
      Role: !GetAtt StateMachineRole.Arn
      Events:
        ExecuteApi:
          Type: Api
          Properties:
            Path: /search
            Method: post
        StatusApi:
          Type: Api
          Properties:
            Path: /search/status
            Method: post
            # Action: DescribeExecution <- Unimplemented
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
  DynamoDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: LateCheckoutHotels
      PrimaryKey:
        Name: id
        Type: String
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer for bs4 and requests
      ContentUri: "layer/"
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
