HOTELS = [
    {"hotelName": "アインズ・イン梅田東", "hotelNo": "345754",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "アパホテル〈御堂筋本町駅前〉", "hotelNo": "386787",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "アパホテル〈御堂筋本町駅東〉（全室禁煙）", "hotelNo": "386585",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "アパホテル〈大阪肥後橋駅前〉（全室禁煙）", "hotelNo": "346744",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "アパホテル〈東梅田 南森町駅前〉", "hotelNo": "323812",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "アパホテル〈淀屋橋 北浜駅前〉", "hotelNo": "369184",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "アパホテル＆リゾート〈御堂筋本町駅タワー〉（全室禁煙）",
        "hotelNo": "376554", "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "イビス大阪梅田", "hotelNo": "339535",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "スーパーホテルPremier大阪・本町　天然温泉　四季彩の湯",
        "hotelNo": "308796", "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "スーパーホテル梅田・肥後橋", "hotelNo": "328798",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "プレミアホテル－CABIN－大阪", "hotelNo": "328778",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "ホテルＷＢＦ本町", "hotelNo": "377707",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "ホテルマイステイズプレミア堂島", "hotelNo": "334326",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "ホテルマイステイズ御堂筋本町", "hotelNo": "314648",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "ホテルマイステイズ堺筋本町", "hotelNo": "304638",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "東急ステイ大阪本町（2020年2月27日グランドオープン）",
        "hotelNo": "307894", "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
    {"hotelName": "ホテルグレイスリー大阪なんば", "hotelNo": "330578", "regionName": "心斎橋・なんば・四ツ橋"},
    {"hotelName": "ダイワロイネットホテル大阪堺筋本町", "hotelNo": "386736",
        "regionName": "大阪駅・梅田駅・福島・淀屋橋・本町"},
]
